### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by luxdlzu** [faa-swim/swim-discovery-service#14] opened 2022-05-26 06:54 UTC
This bug is not revised in the new version.

File: sdm-j/1.0.1/profile.json
Line:
L.126: "required": [ "name", "value", "description", "calculation method", "unit of measure" ]

Should be:
"required": [ "name", "value", "description", "calculation-method", "unit-of-measure" ]

**Comment by wznira** [comment] 2022-06-13 21:16
Duplicate of [Issue #10 ](https://github.com/faa-swim/swim-discovery-service/issues/10#issuecomment-1138212356)

**Closed** 2022-06-13 21:15 UTC
